server:
  port: 8080

spring:
  application:
    name: api
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
