server:
  port: 8081

spring:
  application:
    name: chat
  profiles:
    default: local
  threads:
    virtual:
      enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health
